This notebook follows along with the following video:   

[Exploring Data(part 4) - Bivariate Summaries ](https://www.youtube.com/watch?v=BnBW2CUD0-A&list=PLjPbBibKHH18I0mDb_H4uP3egypHIsvMn&index=12)

Like the previous video
we load up our file by using Rcurl instead of like he does in his videos. The following code sets this up.

First make sure RCurl is installed.

```{r eval=FALSE}
install.packages("RCurl")
```

Then make sure it is loaded:

```{r}
library("RCurl")
```

We read in the dataframe like we have before. 

```{r}
textString<-getURL("https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/usedcars.csv")
df<-read.csv(text=textString, stringsAsFactors=FALSE)
df$transmission <- factor(df$transmission)
```

```{r}
head(df)
```

```{r}
plot(mileage ~ transmission, data=df)
```

```{r}
tapply(df$mileage, df$transmission, mean)
```

```{r}
tapply(df$mileage, df$transmission, sd)
```

```{r}
head(df)
```

```{r}
mean(df$price)
```

```{r}
median(df$price)
```

```{r}
sd(df$price)
```

```{r}
hist(df$price)
```

```{r}
boxplot(df$price)
```

```{r}
boxplot(df$price, horizontal=T)
```

```{r}
hist(df$price)
```

```{r}
plot(price~mileage, data=df)
```

```{r}
plot(price~mileage, data=df, pch=as.integer(transmission))
```

```{r}
plot(price~mileage, data=df, pch=as.integer(transmission), col=as.integer(transmission)+3)
legend("topright", legend=c("AUTO", "MANUAL"), pch=c(1,2), col=c(4,5))
```
