This notebook follows along with the following video:   

[R - Simple Linear Regression (part 2) ](https://www.youtube.com/watch?v=m_8XYVzT1IU&list=PLjPbBibKHH18I0mDb_H4uP3egypHIsvMn&index=15)

Like the previous video we load up our file by using RCurl instead of like he does in his videos.

First make sure RCurl is installed.

```{r eval=FALSE}
install.packages("RCurl")
```

Then make sure it is loaded:

```{r}
library("RCurl")
```
We read in the dataframe like we have before. 

```{r}
textString<-getURL("https://raw.githubusercontent.com/LiviuSosu/Machine-Learning/f647ce8db0ecd9e41240b2cbeee90425c80c0e65/R/Simple%20Linear%20Regression%20Datasets/rent.csv")

rent<-read.csv(text=textString)
```

```{r}
head(rent)
```

```{r}
plot(rent ~ size, data=rent)
```

```{r}
cor(rent$rent, rent$size)
```

```{r}
m1<-lm(rent ~ size, data=rent)
m1
```

```{r}
summary(m1)
```

```{r}
plot(rent ~ size, data=rent)
abline(m1, col="red", lty=2, lwd=2)
```

```{r}
predict(m1, data.frame("size"=10000))
```

```{r}
predict(m1, data.frame("size"=10000), interval="prediction")
```
