This notebook accompanies the video here:

[R - Data Structures (part 2) - data frames](https://www.youtube.com/watch?v=WedM1kG9LLA&list=PLjPbBibKHH18I0mDb_H4uP3egypHIsvMn&index=8)

This cell below loads in the objects from the previous part R-Datastructures(part 1). Just run the cell below to load these objects in.

```{r}
gpa<-c(3.45, 3.97, 2.98, 4)
first_name<- c("Alice", "Alex", "Maria", "John")
pass<-c(TRUE,FALSE,TRUE, TRUE)
gender<-factor(c("F","M","F","M"), levels=c("M","F"))
fcolor <- factor(c("black","red", "red", "blue"))
```

Now you should be all set to follow along with the vidoe where he starts with the `ls` command:

```{r}
ls()
```

```{r}
df1<-data.frame(first_name,gender,gpa, pass,fcolor)
df1
```

```{r}
str(df1)
```

```{r}
df1[1,1]
```

```{r}
df1[3,2]
```

```{r}
df1[3,4]
```

```{r}
df1[3,3]
```

```{r}
df1[2,]
```

```{r}
df1[2:3,]
```

```{r}
df1[c(2,4),]
```

```{r}
df1[,3]
```

```{r}
str(df1)
```

```{r}
df2<-data.frame(first_name,gender,gpa, pass,fcolor, stringsAsFactors=FALSE)
```

```{r}
str(df2)
```

```{r}
df2
```
