---
title: "Diamonds with x,y,z"
jupyter:
  kernelspec:
    display_name: R
    language: R
    name: ir
output:
    ipynbdocument::ipynb_document
---


```{r}
options("scipen"=100, "digits"=4)
diamonds<-read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRg0HUg626uF8xJrZaYZsgOa2Gtfhlnsn00e9fPofb01nRreOucglncXo1xU_cwhueUY8iqC_60ua9t/pub?gid=1994063173&single=true&output=csv")
df<-diamonds[100:200,]
row.names(df)<-NULL
```

```{r}
str(df)
head(df)
```

```{r}
df$cut <- NULL
df$depth <- NULL
df$table<-NULL
df$clarity<-NULL
df$color<-NULL
df$carat<-NULL
str(df)
head(df)
```

```{r}
model<-lm(price~x+y+z,data=df)
summary(model)
```

```{r}
cor(df)
```

```{r}
plot(df, upper.panel=NULL, pch=19)
```

```{r}
modelXandZ<-lm(price~x+z, data=df)
summary(modelXandZ)
```

```{r}
modelY<-lm(price~y, data=df)
summary(modelY)

plot(df$y, df$price, pch=19)
abline(modelY)
```

```{r}
modelX<-lm(price~x, data=df)
summary(modelX)

plot(df$x, df$price, pch=19)
abline(modelX)
```

```{r}
modelZ<-lm(price~z, data=df)
summary(modelZ)

plot(df$z, df$price, pch=19)
abline(modelZ)
```
