---
title: "Predicting Pregnancy"
jupyter:
  kernelspec:
    display_name: R
    language: R
    name: ir
---
```{r}
if (!require("RCurl")) install.packages("RCurl")
library("RCurl")
```
Load the data as a csv file:

```{r}
url<- "https://docs.google.com/spreadsheets/d/e/2PACX-1vSjtQqcKaaobKkhQXaP2b6gcbQkaKJabjPz2k_hfHj2VEqcSW-I0BiCRpz9VkoQgpcylTUNSp1Opt4P/pub?gid=1389299652&single=true&output=csv"
textString<-getURL(url)
df<-read.csv(text=textString)
```

```{r}
str(df)
```

```{r}
dfFactors <- df
dfFactors[] <- lapply(dfFactors, factor)
str(dfFactors)
```

```{r}

cv = function(x,y) {
  return (round(sqrt(chisq.test(x, y, correct=FALSE)$statistic /length(x)),2))
}

cramersv <- apply(df, 2, function(x) cv(x,dfFactors$Pregnant))  
cramersvDf<- data.frame(cramersv)
cramersvDf
```

Let's run a logistic regression:

```{r}
options("scipen"=100, "digits"=4)
logisticModel <- glm(Pregnant ~.,family=binomial(link='logit'),data=dfFactors)
summary(logisticModel)
```

`BodyPillow` and `SeaBands` are not significant in this model.


What about computing correlations on the int versions: 

```{r}
correlations <- apply(df, 2, function(x) cor(x,df$Pregnant))  
correlationsDf<- data.frame(correlations)
correlationsDf
```

And then just regular regression: 
```{r}
model <- lm(Pregnant ~.,data=df)
summary(model)
```

Lets look at some xtabs for 
```{r}
#xtabs(formula=~Pregnant+FolicAcid, data=dfFactors)
```

```{r}
#xtabs(formula=~Pregnant+MaternityClothes, data=dfFactors)
```

```{r}
#xtabs(formula=~Pregnant+BirthControl, data=dfFactors)
```
