---
title: "Cart"
jupyter:
  kernelspec:
    display_name: R
    language: R
    name: ir
---

```{r}
install.packages("devtools")
devtools::install_github("alistaire47/read.so")
library(read.so)
```

```{r}
options("scipen"=100, "digits"=4)
if(!require("readr")) install.packages("readr")
if(!require("rpart")) install.packages("rpart")
if(!require("rpart.plot")) install.packages("rpart.plot")
if(!require("ISLR")) install.packages("ISLR")
library("readr")
library("rpart")
library("rpart.plot")
library("ISLR")
```

```{r}
# this is the purchased data
url<-"https://docs.google.com/spreadsheets/d/e/2PACX-1vTx21HIv4xKL2c94OLQzMiNPmv5YXw-vAy3dRBL0gnknSMKMK4Ur_4nYGGyDtvS20iU3_r-_zZfQQmj/pub?gid=0&single=true&output=csv"
df<-read.csv(url, stringsAsFactor=TRUE)
```

```{r}
write.so(df)
```

```{r}
str(df)
head(df)
print(df)
```

```{r}
model <- rpart(Purchased~., data=df, method="class", control = rpart.control(minsplit=1,maxdepth=4))
rpart.plot(model)
```

Original table:

| Salary | Age | Purchased |
|--------|-----|-----------|
| 53700  | 41  | no        |
| 65300  | 37  | no        |
| 48900  | 45  | yes       |
| 64800  | 49  | yes       |
| 44200  | 30  | no        |
| 55900  | 57  | yes       |
| 48600  | 26  | no        |
| 72000  | 60  | yes       |
| 45300  | 34  | no        |
| 73200  | 52  | yes       |

```{r}
markdown<-'
| Salary | Age | Purchased |
|--------|-----|-----------|
| 53700  | 41  | no        |
| 65300  | 37  | no        |
| 48900  | 45  | yes       |
| 64800  | 49  | yes       |
| 69200  | 30  | yes       |
| 55900  | 57  | yes       |
| 48600  | 26  | no        |
| 72000  | 60  | yes       |
| 45300  | 34  | no        |
| 69000  | 32  | yes       |
| 73200  | 52  | yes       |
'

df<-as.data.frame(read_md(markdown))
str(df)
head(df)
str(df$Age)
model <- rpart(Purchased~., data=df, method="class", control = rpart.control(minsplit=1,maxdepth=1))
rpart.plot(model)
model
```

```{r}
```
