---
title: "Rvest how to"
jupyter:
  kernelspec:
    display_name: R
    language: R
    name: ir
---

```{r echo=T, results='hide', message=F, warning=F}
if (!require("rvest")) install.packages("rvest")
library("rvest")
```

We are going to read in a page at [http://quotes.toscrape.com/](http://quotes.toscrape.com/) and get the items on it:

```{r}
url<-"http://quotes.toscrape.com/"
webpage <- read_html(url)
```

Use the selectorgadget to select the quotes on the page:

```{r}
nodes <- html_nodes(webpage, ".text")
quotes <- html_text(nodes)
str(quotes)
```

Lets take a look at the first few values:

```{r}
head(quotes)
```

Next lets get the authors on the page:

```{r}
nodes <- html_nodes(webpage, ".author")
author <- html_text(nodes)
str(author)
```

Lets take a look at the first few values:

```{r}
head(author)
```

Lets make a dataframe with these columns:

```{r}
df<-data.frame(author,quotes)
print(df)
```

```{r}
nodes <- html_nodes(webpage, "span a")
tags <- html_text(nodes)
str(tags)
```

Lets take a look at the first few values:

```{r}
head(tags)
```

Lets make a dataframe with these columns:

```{r}
df<-data.frame(author,quotes, tags)
print(df)
```
