---
Title: "Shaded Area Under Standard Normal Curve"
params: 
  a: -0.64 
  b: 2.03
---

```{r params, include=FALSE}
library(ggplot2)
a <- params$a
b <- params$b

drawGraph<- function() {
dat <- data.frame(x=c(-3.5, 3.5))
ggplot(dat, aes(x=x)) +
  stat_function(fun=dnorm) +
  stat_function(fun=dnorm, xlim = c(a,b), geom="area", fill="green", alpha=0.3) +
  labs(x = "z", y = "") +
  geom_hline(yintercept=0) +
  scale_x_continuous(breaks = seq(-3, 3, by = 1.0)) +
#  scale_y_continuous(breaks = seq(0, .4, by = 0.2)) +
  scale_y_continuous(breaks = NULL) +
  annotate("text", x = b, y = -0.02, label = sprintf("z=%s", b)) +
  annotate("text", x = a, y = -0.02, label = sprintf("z=%s", a))
#  annotate("text", x = 0, y = -0.01, label = " ")
}

```

## Area Under Standard Normal Curve

First we find the left tail area up the right endpoint using the table:

```{r area, echo=FALSE, fig.width=6, fig.height=3}
dat <- data.frame(x=c(-3.5, 3.5))
ggplot(dat, aes(x=x)) +
  stat_function(fun=dnorm) +
  stat_function(fun=dnorm, xlim = c(a,b), geom="area", fill="green", alpha=0.3) +
  labs(x = "z", y = "") +
  geom_hline(yintercept=0) +
  scale_x_continuous(breaks = seq(-3, 3, by = 1.0)) +
#  scale_y_continuous(breaks = seq(0, .4, by = 0.2)) +
  scale_y_continuous(breaks = NULL) +
  annotate("text", x = b, y = -0.02, label = sprintf("z=%s", b)) +
  annotate("text", x = a, y = -0.02, label = sprintf("z=%s", a))
#  annotate("text", x = 0, y = -0.01, label = " ")
```

left tail area = d

Then we find the area up to the left endpoint: 

