---
Title: Standard Normal LookUp
params:
  z:
    input: slider
    label: This is Z
    max: 3.5
    min: -3.5
    step: 0.01
    value: 1.23
---

Here is te table...

```{r params, echo=FALSE}
# in this code block we just set x,mu,sigma so we can use them below.
z<-params$z; 
```

```{r tablesetup, echo = FALSE}
library(knitr)

colTitles <- c(" .00"," .01"," .02"," .03"," .04"," .05"," .06"," .07"," .08"," .09")
zStartOfLastRow <- 3.4
numRows <- zStartOfLastRow*10+1

# Pos z-table rows go like this:  0.0, 0.1,... , 2.9, 3.0
# Matrix of positive z-values
posZValues <- matrix(nrow=numRows, ncol=10)

for(i in 1:numRows) {
  for(j in 1:10) {
    posZValues[i, j] = (i-1)*.1 + (j-1)*(.01)
  }
}

# left tail areas like '0.9324' 
posZAreas <- format(round(pnorm(posZValues),4),nsmall=4)

# Has format '0.3742', so this lops off the '0' at start.
posZAreas <- substring(posZAreas, 2)

# eg this is .1, .2, .3, ..., 3.0 
posRowNames <- seq(.1, zStartOfLastRow, by=.1)
rownames(posZAreas) <- c("0.0",posRowNames)
colnames(posZAreas) <- colTitles

# Neg z-table rows go like this: -3.0,-2.9,... ,-0.1, 0.0 
# Matrix of negative z-values
negZValues <- matrix(nrow=numRows, ncol=10)
for(i in 1:numRows) {
  for(j in 1:10) {
    negZValues[i, j] = (numRows-i)*(-.1) - (j-1)*(.01)
  }
}

negZAreas <- format(round(pnorm(negZValues),4),nsmall=4)
negZAreas <- substring(negZAreas, 2)

# eg this is -3.0, -2.9, ... , -.1
negRowNames <- seq(-zStartOfLastRow,-.1,by=.1)
rownames(negZAreas) <- c(negRowNames, "0.0")
colnames(negZAreas) <- colTitles
```

## Standard Normal Table 

First find the negative z-values:  

```{r negtable, echo = FALSE}
kable(negZAreas)
```

This is second half of the table:

```{r postable, echo = FALSE}
kable(posZAreas)
```
