---
title: "Webscraping Tradesy"
jupyter:
  kernelspec:
    display_name: R
    language: R
    name: ir
output:
    ipynbdocument::ipynb_document
---

Install rvest if needed and then load it:

```{r echo=T, results='hide', message=F, warning=F}
options(repr.plot.width=7, repr.plot.height=7)
knitr::opts_chunk$set(fig.width=7, fig.height=7)
if (!require("rvest")) install.packages("rvest")
library("rvest")
```
```{r}
url <- "https://www.tradesy.com/on-sale/?page=1&num_per_page=192"
webpage <- read_html(url)
```

```{r}
nodes <- html_nodes(webpage, ".item-brand")
brand <- html_text(nodes)
brand<-trimws(brand)
str(brand)
allbrands<-brand
```

```{r}
nodes <- html_nodes(webpage, ".item-title")
title <- html_text(nodes)
title<-trimws(title)
str(title)
```

```{r}
nodes <- html_nodes(webpage, ".item-price>em")
price<- html_text(nodes)
price<-gsub("\\s", "", price)
price<-gsub(",","",price)
price<-sub("$", "", price, fixed=TRUE)
price<-as.numeric(price)
allprices<-as.numeric(price)
str(price)
```

```{r}
nodes <- html_nodes(webpage, ".item-price")
orig<- html_text(nodes)
orig<-gsub("\\s", "", orig)
orig<-gsub(",","",orig)
orig<-sub("$", "", orig, fixed=TRUE)
orig<-strsplit(orig, "$", fixed=TRUE)
orig<-lapply(orig, function(v){v[2]}) 
orig<-unlist(orig)
orig<-as.numeric(orig)
str(orig)
```

```{r}
brand <- brand[!is.na(orig)]
title <- title[!is.na(orig)]
price<- price[!is.na(orig)]
orig <- orig[!is.na(orig)]
str(brand)
str(title)
str(price)
str(orig)
```

```{r}
discount<- round((orig - price)/orig * 100)
df<-data.frame(brand, title, price, orig, discount)
str(df)
head(df)
```

```{r}
barplot(table(allbrands), las=2, horiz=TRUE, main="Brands", cex.names=.5)
```

```{r}
hist(discount, breaks=20, main="Discounts")
```

```{r}
hist(allprices, xlab="prices", breaks=20, main="Prices")
```

```{r}
plot(orig,price, pch=19, main="Price vs Original")
```

